In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
widths = [1]*32
df = pd.read_fwf('digitdata/optdigits-orig_train.txt', widths=widths, header=None, skiprows=lambda x : (x+1) % 33 == 0)
# df
df_Y = pd.read_fwf('digitdata/optdigits-orig_train.txt', widths=[2], header=None, skiprows=lambda x : (x+1) % 33 != 0)
print(len(df_Y))

2436


In [3]:
df_trainX = pd.DataFrame(df.values.reshape(2436, -1))
df_trainY = df_Y
df_trainY.columns = ['label']
# df_Y

In [4]:
n = 4
m = 2
length = int(32*32/n/m)

df_disjoint = pd.DataFrame(np.nan, index=range(2436), columns=range(length))

In [5]:
for idx, image in df_trainX.iterrows():
    for i in range(length):
        temp = ''
        c = 0
        if (i%(32/m) == 0 and not i == 0):
            c += 32
        for k in range(n):
            for l in range(m):
                temp += str(image[m*i+l+c+ 32*k])
        df_disjoint.iloc[idx, i] = int(temp, 2)

0    1    2    3      4      5      6      7      8      9   ...   \
0     0.0  0.0  0.0  1.0    3.0   15.0  127.0  255.0  191.0   47.0 ...    
1     0.0  0.0  0.0  0.0    7.0  127.0  255.0  255.0   47.0    2.0 ...    
2     0.0  0.0  0.0  0.0    5.0   63.0  127.0  255.0  255.0  255.0 ...    
3     0.0  0.0  0.0  0.0    0.0    0.0    1.0    3.0   15.0  127.0 ...    
4     0.0  0.0  0.0  0.0    0.0   31.0  127.0  191.0   43.0    0.0 ...    
5     0.0  0.0  0.0  0.0   21.0  255.0  255.0  255.0  191.0   11.0 ...    
6     0.0  0.0  0.0  0.0    0.0    1.0   31.0   63.0   63.0  127.0 ...    
7     0.0  0.0  0.0  0.0    1.0  127.0  175.0   15.0   15.0   15.0 ...    
8     0.0  0.0  0.0  0.0  127.0  255.0    2.0    1.0   63.0  255.0 ...    
9     0.0  0.0  0.0  0.0    0.0    7.0   31.0  255.0  255.0   47.0 ...    
10    0.0  0.0  0.0  0.0    1.0   31.0  255.0   63.0   63.0  255.0 ...    
11    0.0  0.0  0.0  0.0    0.0    0.0    0.0   21.0  255.0  255.0 ...    
12    0.0  0.0  0.0  0.0    0.0    0.0    1.0    7.0   31.0  255.0 ...    
13    0.0  0.0  0.0  0.0    1.0   95.0  191.0   47.0   15.0    3.0 ...    
14    0.0  0.0  0.0  0.0    7.0   15.0   31.0   63.0   63.0   47.0 ...    
15    0.0  0.0  0.0  1.0   23.0   63.0  255.0  191.0   47.0   11.0 ...    
16    0.0  0.0  0.0  0.0    0.0    0.0    0.0    1.0   15.0  127.0 ...    
17    0.0  0.0  0.0  0.0    0.0   31.0   63.0   63.0  255.0  255.0 ...    
18    0.0  0.0  0.0  0.0    0.0    1.0   15.0   15.0   63.0  127.0 ...    
19    0.0  0.0  0.0  0.0    0.0    0.0    0.0    3.0   31.0  255.0 ...    
20    0.0  0.0  0.0  0.0    1.0    7.0   31.0   63.0  127.0  255.0 ...    
21    0.0  0.0  0.0  0.0    0.0   15.0   15.0   63.0  127.0   63.0 ...    
22    0.0  0.0  0.0  0.0    0.0    7.0   31.0   63.0   63.0  127.0 ...    
23    0.0  0.0  0.0  0.0    0.0    1.0    3.0    3.0   31.0   63.0 ...    
24    0.0  0.0  0.0  0.0   64.0  255.0  255.0   47.0    2.0    0.0 ...    
25    0.0  0.0  0.0  0.0    7.0   63.0  255.0  255.0   63.0   47.0 ...    
26    0.0  0.0  0.0  0.0    0.0    5.0   31.0  255.0  175.0   11.0 ...    
27    0.0  0.0  0.0  0.0    0.0    0.0   15.0   63.0  255.0   43.0 ...    
28    0.0  0.0  0.0  0.0    0.0    0.0    0.0    0.0    5.0  255.0 ...    
29    0.0  0.0  0.0  0.0    7.0   15.0   15.0   31.0   63.0  127.0 ...    
...   ...  ...  ...  ...    ...    ...    ...    ...    ...    ... ...    
2406  0.0  0.0  0.0  0.0    0.0    0.0    0.0    0.0    1.0    7.0 ...    
2407  0.0  0.0  0.0  1.0   31.0  255.0  255.0  255.0  191.0   11.0 ...    
2408  0.0  0.0  0.0  0.0    7.0   15.0   31.0   63.0  255.0  255.0 ...    
2409  0.0  0.0  0.0  0.0    1.0   15.0   31.0  127.0  191.0   47.0 ...    
2410  0.0  0.0  1.0  7.0   15.0   31.0   31.0   63.0   63.0  127.0 ...    
2411  0.0  0.0  0.0  7.0  127.0  255.0  255.0  255.0  175.0    2.0 ...    
2412  0.0  0.0  0.0  0.0    0.0    1.0    7.0   31.0  255.0  255.0 ...    
2413  0.0  0.0  0.0  0.0    7.0   63.0  191.0   63.0   15.0    0.0 ...    
2414  0.0  0.0  0.0  0.0    0.0    0.0  127.0  255.0  255.0   63.0 ...    
2415  0.0  0.0  0.0  0.0    0.0    0.0    1.0   63.0  183.0   63.0 ...    
2416  0.0  0.0  0.0  0.0    0.0    0.0    0.0   63.0  255.0  234.0 ...    
2417  0.0  0.0  0.0  0.0    1.0  127.0  255.0   63.0   63.0   63.0 ...    
2418  0.0  0.0  0.0  0.0    1.0    7.0  127.0  255.0  127.0  255.0 ...    
2419  0.0  0.0  0.0  0.0    0.0    1.0   63.0  255.0  255.0  255.0 ...    
2420  0.0  0.0  0.0  0.0    0.0    1.0   31.0  127.0  255.0  255.0 ...    
2421  0.0  0.0  0.0  0.0    0.0    0.0    0.0   87.0  255.0  190.0 ...    
2422  0.0  0.0  0.0  0.0    0.0   13.0   63.0  191.0   47.0   11.0 ...    
2423  0.0  0.0  0.0  0.0    0.0    0.0    0.0   23.0  127.0  255.0 ...    
2424  0.0  0.0  0.0  0.0   21.0  127.0  255.0  255.0  255.0  255.0 ...    
2425  0.0  0.0  0.0  0.0    0.0   15.0   31.0   63.0  255.0  255.0 ...    
2426  0.0  0.0  0.0  0.0    0.0    0.0    5.0   63.0  255.0  255.0 ...    
2427  0.0  0.0  0.0  1.0   23.0

In [6]:
df = pd.read_fwf('digitdata/optdigits-orig_test.txt', widths=widths, header=None, skiprows=lambda x : (x+1) % 33 == 0)
df_Y = pd.read_fwf('digitdata/optdigits-orig_test.txt', widths=[2], header=None, skiprows=lambda x : (x+1) % 33 != 0)


In [7]:
df_testX = pd.DataFrame(df.values.reshape(444, -1))
df_testY = df_Y
df_testY.columns = ['label']

In [8]:
df_test = pd.DataFrame(np.nan, index=range(444), columns=range(length))

for idx, image in df_testX.iterrows():
    for i in range(length):
        temp = ''
        c = 0
        if (i%(32/m) == 0 and not i == 0):
            c += 32
        for k in range(n):
            for l in range(m):
                temp += str(image[m*i+l+c+ 32*k])
        df_test.iloc[idx, i] = int(temp, 2)

0    1    2     3      4      5      6      7      8      9   ...   \
0    0.0  0.0  0.0   0.0    0.0    0.0   15.0   63.0  191.0   47.0 ...    
1    0.0  0.0  0.0  21.0  255.0  255.0  255.0  191.0   11.0    0.0 ...    
2    0.0  0.0  0.0   0.0   63.0   63.0   63.0   63.0  255.0  255.0 ...    
3    0.0  0.0  0.0   0.0    0.0    0.0    0.0    1.0  127.0  255.0 ...    
4    0.0  0.0  0.0   0.0    0.0    0.0    1.0  127.0  255.0  190.0 ...    
5    0.0  0.0  0.0   0.0    0.0    0.0   15.0  127.0  255.0   47.0 ...    
6    0.0  0.0  0.0   0.0    3.0   31.0   63.0  191.0   14.0    0.0 ...    
7    0.0  0.0  0.0   0.0    7.0   63.0  255.0  255.0   63.0   11.0 ...    
8    0.0  0.0  0.0   7.0   63.0  255.0  255.0   63.0   10.0    0.0 ...    
9    0.0  0.0  0.0   1.0   31.0  127.0  255.0  255.0   63.0   47.0 ...    
10   0.0  0.0  0.0   0.0    0.0   23.0  127.0   43.0    0.0    0.0 ...    
11   0.0  0.0  0.0   0.0    0.0    0.0   95.0  255.0  175.0    0.0 ...    
12   0.0  0.0  0.0   0.0    0.0    3.0   63.0  255.0   47.0    2.0 ...    
13   0.0  0.0  0.0   0.0    1.0   95.0  255.0   63.0  127.0   63.0 ...    
14   0.0  0.0  0.0   0.0    3.0   15.0  255.0   63.0   47.0    2.0 ...    
15   0.0  0.0  0.0  31.0   63.0   63.0   63.0  255.0  255.0  255.0 ...    
16   0.0  0.0  0.0   0.0    0.0    0.0    1.0   63.0  255.0  255.0 ...    
17   0.0  0.0  0.0   0.0    0.0    0.0    1.0   63.0  191.0    2.0 ...    
18   0.0  0.0  0.0   0.0    1.0   31.0  255.0  255.0  255.0  255.0 ...    
19   0.0  0.0  0.0   0.0    1.0   31.0   63.0   63.0   63.0   63.0 ...    
20   0.0  0.0  0.0   0.0    3.0   15.0   63.0  255.0  255.0  191.0 ...    
21   0.0  0.0  0.0   0.0    3.0  127.0  255.0  255.0  255.0  255.0 ...    
22   0.0  0.0  0.0   7.0   31.0   63.0  255.0  255.0  255.0  191.0 ...    
23   0.0  0.0  0.0   0.0    0.0    1.0   15.0  127.0  255.0  191.0 ...    
24   0.0  0.0  0.0   0.0    7.0  255.0  255.0  255.0  255.0  255.0 ...    
25   0.0  0.0  0.0   0.0   15.0   31.0   63.0  255.0  255.0  255.0 ...    
26   0.0  0.0  0.0   0.0    3.0   15.0   31.0   63.0  255.0  255.0 ...    
27   0.0  0.0  0.0   0.0    1.0   15.0  127.0  191.0   47.0    3.0 ...    
28   0.0  0.0  0.0   0.0    0.0    0.0   23.0  191.0   43.0    0.0 ...    
29   0.0  0.0  0.0   0.0    0.0    0.0    3.0   63.0  255.0  254.0 ...    
..   ...  ...  ...   ...    ...    ...    ...    ...    ...    ... ...    
414  0.0  0.0  0.0   0.0    0.0   31.0  127.0  255.0   63.0   10.0 ...    
415  0.0  0.0  0.0   0.0   23.0  255.0  191.0    0.0    0.0    0.0 ...    
416  0.0  0.0  0.0   0.0    1.0    7.0   15.0   95.0  255.0  255.0 ...    
417  0.0  0.0  0.0   0.0    0.0    0.0    7.0   95.0  255.0  186.0 ...    
418  0.0  0.0  0.0   0.0    7.0   31.0  255.0  255.0  255.0  255.0 ...    
419  0.0  0.0  0.0   0.0    5.0  255.0  175.0    2.0    0.0    0.0 ...    
420  0.0  0.0  0.0   3.0   31.0  255.0  255.0  255.0  255.0  255.0 ...    
421  0.0  0.0  0.0   0.0    0.0   31.0  255.0  255.0   47.0    0.0 ...    
422  0.0  0.0  0.0   1.0   15.0  127.0  255.0  255.0  255.0  255.0 ...    
423  0.0  0.0  0.0   0.0    1.0   95.0  255.0  255.0  255.0   63.0 ...    
424  0.0  0.0  0.0   0.0    3.0   63.0  127.0  255.0  255.0  255.0 ...    
425  0.0  0.0  0.0   1.0   23.0  255.0  255.0  255.0  255.0  191.0 ...    
426  0.0  0.0  0.0   5.0  255.0  255.0  255.0  191.0   43.0    0.0 ...    
427  0.0  0.0  0.0   1.0   95.0  255.0  255.0  255.0  191.0   10.0 ...    
428  0.0  0.0  0.0   0.0   15.0  255.0  255.0  255.0  255.0   63.0 ...    
429  0.0  0.0  0.0   0.0    0.0    3.0   63.0  255.0  255.0  255.0 ...    
430  0.0  0.0  0.0   7.0   63.0  255.0  255.0  255.0   47.0    3.0 ...    
431  0.0  0.0  0.0   0.0   29.0  255.0  255.0  255.0  255.0  191.0 ...    
432  0.0  0.0  0.0   0.0    0.0    0.0   29.0  255.0  255.0  255.0 ...    
433  0.0  0.0  0.0  21.0  255.0   63.0  127.0  255.0  255.0  255.0 ...    
434  0.0  0.0  0.0   0.0    1.0   15.0  127.0  255.0  255.0  191.0 ...    
435  0.0  0.0  0.0   0.0    0.

In [9]:
class_count = np.array((df_trainY['label'].value_counts().sort_index()))
class_count

array([240, 250, 246, 251, 241, 237, 239, 250, 231, 251])

In [10]:
class_log_prior = np.log(class_count) - np.log(len(df_trainY))
class_log_prior

array([-2.31747371, -2.27665171, -2.29278109, -2.27265969, -2.3133157 ,
       -2.33005249, -2.32164908, -2.27665171, -2.35569492, -2.27265969])

In [11]:
#feature_count.append(np.array([[[sum(df_disjoint[df_trainY['label'] == i].iloc[:,j] ) for i in range(10)] for j in range(256)]).T)


feature_MF = []
for val in range(2**(n*m)):
    feature_makeval = np.copy(df_disjoint)
    feature_makeval[df_disjoint != val] = 0
    feature_makeval[df_disjoint == val] = 1
#     only count the frenqucy of certain feature whose value == val
    feature_count = np.array([[sum(feature_makeval[df_trainY['label'] == i][:,j]) for i in range(10)] for j in range(length)]).T
    feature_MF.append(feature_count)
feature_MF = np.swapaxes(feature_MF, 0, 1)
feature_MF = np.swapaxes(feature_MF, 1, 2)
feature_MF = np.reshape(feature_MF, (10, (2**(n*m))*length))

array([[240.,   0.,   0., ...,   0.,   0.,   0.],
       [250.,   0.,   0., ...,   0.,   0.,   0.],
       [246.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [250.,   0.,   0., ...,   0.,   0.,   0.],
       [231.,   0.,   0., ...,   0.,   0.,   0.],
       [251.,   0.,   0., ...,   0.,   0.,   0.]])

In [12]:
def calc_feature_log_prob(feature_MF, k=1):
    smoothed_fc = feature_MF + k
    smoothed_cc = smoothed_fc.sum(axis=1)
    return (np.log(smoothed_fc) - np.log(smoothed_cc.reshape(-1, 1)))

In [13]:
feature_log_prob = [calc_feature_log_prob(feature_MF, k=0.1), \
                    calc_feature_log_prob(feature_MF, k=1), \
                    calc_feature_log_prob(feature_MF, k=5), \
                    calc_feature_log_prob(feature_MF, k=10)]

In [ ]:
test_MF = np.zeros((444 , length, (2**(n*m))  ))
for i in range(444):
    for j in range(length):
        for k in range(2**(n*m)):
            test_MF[i, j, k] = 1 if df_test.iloc[i, j] == k else 0

In [ ]:
test_MF = np.reshape(test_MF, (444, length * (2**(n*m))))        
test_MF  

In [ ]:
joint_log_likelihood = [test_MF @ feature_log_prob[0].T + class_log_prior, \
                        test_MF @ feature_log_prob[1].T + class_log_prior, \
                        test_MF @ feature_log_prob[2].T + class_log_prior, \
                        test_MF @ feature_log_prob[3].T + class_log_prior]
# joint_log_likelihood

In [ ]:
pred = [np.argmax(joint_log_likelihood[0], axis=1), \
        np.argmax(joint_log_likelihood[1], axis=1), \
        np.argmax(joint_log_likelihood[2], axis=1), \
        np.argmax(joint_log_likelihood[3], axis=1)]

In [ ]:
smooth_k = [0.1, 1, 5, 10]
for i in range(4):
    y_pred = pd.Series(pred[i])
    df_confusion = pd.crosstab(df_testY['label'], y_pred)

    conf_percent = df_confusion.values / df_confusion.sum(axis=1).values.reshape(-1,1)
    df_conf_percent = round(pd.DataFrame(conf_percent).rename_axis('Actual').rename_axis('Prediction', axis=1), 4)*100
    print('Test set Confusion Matrix: Actual vs. Prediction (Smoothing value k = {})'.format(smooth_k[i]))
    display(df_conf_percent)
    display(pd.DataFrame(np.diag(df_conf_percent), columns=['Accuracy']))
    print('Average Accuracy: {}'.format(np.mean(np.diag(df_conf_percent))))
    print('\n')
# df_conf_percent

### Choose the smoothing parameter with the best average accuracy (k=5)

In [ ]:
LL_pred = pd.concat([pd.DataFrame(joint_log_likelihood[2]), df_testY], axis=1)
# LL_pred

In [ ]:
for index in range(10):
    i_most = LL_pred[LL_pred['label']==index].iloc[:,index].idxmax()
    i_least = LL_pred[LL_pred['label']==index].iloc[:,index].idxmin()
    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(10,6))
    ax1.imshow(df_testX.iloc[i_most,:].values.reshape((32,32)), cmap='Greys')
    ax2.imshow(df_testX.iloc[i_least,:].values.reshape((32,32)), cmap='Greys')
    ax1.set_title('Visualizing most prototypical sample for {}'.format(index))
    ax2.set_title('Visualizing least prototypical sample for {}'.format(index))
    ax1.axis('off')
    ax2.axis('off')
    plt.subplots_adjust(wspace=0.5)
    plt.show()


In [ ]:
def plot_log_odds_ratio(c1, c2):
    f, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(15,4))
    ax1 = sns.heatmap(feature_log_prob[2][c1].reshape((32,32)), ax=ax1, cmap='jet', xticklabels=False, yticklabels=False)
    ax2 = sns.heatmap(feature_log_prob[2][c2].reshape((32,32)), ax=ax2, cmap='jet', xticklabels=False, yticklabels=False)
    ax3 = sns.heatmap((feature_log_prob[2][c1] - feature_log_prob[2][c2]).reshape((32,32)), ax=ax3, cmap='jet', xticklabels=False, yticklabels=False)
    plt.subplots_adjust(wspace=0.3)
    plt.show()

In [ ]:
for i, cls in enumerate(zip([2,5,3,4], [8,9,9,7])):
    plot_log_odds_ratio(cls[0], cls[1])